name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      # BACKEND (TypeScript)
      - name: Compilar y reiniciar Backend
        run: |
          source ~/.nvm/nvm.sh
          cd backend
          npm install
          cp ~/backend.env ./src/config/.env 2>/dev/null || true
          npm run build
          setsid pm2 restart api-backend || setsid pm2 start dist/index.js --name api-backend
          pm2 save

      # FRONTEND
      - name: Compilar y reiniciar Frontend
        run: |
          source ~/.nvm/nvm.sh
          cd frontend
          npm install
          npm run build
          setsid pm2 restart frontend-app || setsid pm2 start "npx serve -s dist -l 1638" --name frontend-app
          pm2 save
          